### ISSUE TITLE
Add Firebase Performance

### ISSUE THREAD

**Issue by lupas** [lupas/nuxt-fire#31]
Add firebase performance to nuxt-fire.

See here:
https://firebase.google.com/docs/perf-mon/get-started-web

**Comment by lupas** [comment]
I tried adding Firebase performance but run into some issues, see branch here:
https://github.com/lupas/nuxt-fire/tree/addFirePerf

When importing Firebase performance both on server-side and client side, like so....
```js
<%= options.useOnly.includes('performance') ? "import 'firebase/performance'" : "" %>
```
I get the following error:
```
window is not defined
```

When only importing Firebase Performance on client side, like so...
```js
<%= (process.browser && options.useOnly.includes('performance')) ? "import 'firebase/performance'" : "" %>
```
for some unexplainable reason firebase.performance still does not work and I get the following issue:
```
TypeError: firebase_app__WEBPACK_IMPORTED_MODULE_2___default.a.performance is not a function
```

Something about SSR and Firebase.performance seems to cause problems, but I couldn't really figure out what.

🌏Won't have time to look further into this since I'm travelling for a while, if anyone knows a way to make this work please let me know below :)

**Comment by lupas** [comment]
With the newest version of Firebase the integration seems to work, but throws a **Could not register Firebase Installation** error message:

```
Uncaught (in promise) FirebaseError: Installations: Could not register Firebase Installation. (installations/create-installation-failed).
    at http://localhost:3000/_nuxt/vendors.app.js:40356:45
    at step (http://localhost:3000/_nuxt/vendors.app.js:40995:23)
    at Object.next (http://localhost:3000/_nuxt/vendors.app.js:40976:53)
    at fulfilled (http://localhost:3000/_nuxt/vendors.app.js:40966:58)
```

Will investigate more.

**Comment by lupas** [comment]
Okay, got it to work. Firebase JS SDK v.6.3.2 did the trick :-) 

Firebase Performance is now added with Nuxt-Fire v2.0.0.
